name: ar_drawing
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.9+15

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  get: ^4.6.6

  flutter_cache_manager: ^3.3.1
  cached_network_image: ^3.3.1
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  lottie: ^2.7.0

  shared_preferences: ^2.2.2

  fluttertoast: ^8.2.4
  url_launcher: ^6.2.4
  intl: ^0.18.1
  package_info_plus: ^4.2.0
  image_picker: ^1.0.7
  meta: ^1.9.1
  vector_math: ^2.1.4
  camera: ^0.10.5+9
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  connectivity_plus: ^5.0.2
  dio: ^5.4.1
  app_settings: ^5.1.1
  gap: ^3.0.1
  in_app_purchase: ^3.1.13
  http: ^1.1.0
  path: ^1.8.3
  path_provider: ^2.1.2
  video_player: ^2.8.2
  share_plus: ^7.2.2
  image_gallery_saver: ^2.0.3
  printing: ^5.12.0
  permission_handler: ^11.0.1

  firebase_remote_config: ^4.3.8
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.9
  firebase_analytics: ^10.8.0
  store_redirect: ^2.0.1
  in_app_purchase_storekit: ^0.3.8+1
  image: ^4.1.7
  chewie: ^1.7.5
  flutter_staggered_grid_view: ^0.7.0
  google_mobile_ads: ^4.0.0
  wakelock_plus: ^1.1.4
  sqflite: ^2.3.2
  flutter_inappwebview: ^6.0.0
  device_info: ^2.0.3
  applovin_max: ^3.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/src/resource/png/
    - lib/src/resource/svg/
    - lib/src/resource/lottie/

  fonts:
    - family: ShortStack
      fonts:
        - asset: lib/src/resource/font/short_stack.ttf
          weight: 400