const englishString = {
  "unknown_error": "Unknown error",
  "no_internet": "No internet connection",
  "not_available": "Not available",
  "can_not_connect_store": "Can not connect store",
  "purchase_fail": "Purchase is failed",
  "setting": "Settings",
  "more": "More",
  "more_app": "More app",
  "privacy_policy": "Privacy Policy",
  "term_of_condition": "Term of Condition",
  "term_of_service": "Terms of Service",
  "contact_us": "Contact us",
  "restore": "Restore",
  "notice": "Notice",
  "close": "Close",
  "continues": "Continue",
  "errorLocation00":
      "Enable device location permission to update  temperature and weather condition",
  "errorLocation01": "Please enable location services",
  "errorLocation02":
      "Update temperature and weather conditions of your location by allowing access to your precise location",
  "errorLocation03":
      "Update temperature and weather conditions of your location by allowing access to your precise location",
  "errorLocation04":
      "Please check your GPS settings and allow the app to access your location",
  "intro1_1": "Learn to draw",
  "intro1_2": "",
  "intro1_3": "with your phone",
  "intro2_1": "Templates album",
  "intro2_2": "",
  "intro2_3": "to draw everything",
  "intro3_1": "Copy image to paper ",
  "intro3_2": "",
  "intro3_3": "with AR sketch",
  "intro4_1": "",
  "intro4_2": "Trace with",
  "intro4_3": " amazing drawing",
  "str_remove_ads": "Find My Device",
  "remove_ads1": "Find your phone without being interrupted",
  "remove_ads2": "One time purchase only",
  "remove_ads3": "Life time access",
  "remove_ads4": "Remove ads forever",
  "loading_ad": "Loading ads…",
  "language": "Language",
  "english": "English",
  "next": "Next",
  "skip": "Skip",
  "request_per": "Request permission",
  "allow_per": "Allow permission to use function",
  "not_now": "Not now",
  "allow": "Allow",
  "record_permission": "Record Permission",
  "cancel": "Cancel",
  "go_to_setting": "Go to setting",
  "OK": "OK",
  "no": "No",
  "yes": "Yes",
  "close_app": "Close app",
  "want_exit": "Are you sure want to exit?",
  "unlock_all": "Unlock all the features",
  "ads_are_about": "Ads are about to show …",
  "loading": "Loading ...",
  "let_start": "Let's start",
  "notification": "Notification",
  'rate': "Rate",
  'draw': "Draw",
  'term': "Term of condition",
  'privacy': "Privacy policy",
  'contact': "Contact",
  'goPremium': "Go Premium",
  "sub_rate": "Please rate 5 stars to motivate us. Thanks for your support!",
  "arDraw": "Ar Draw",
  "pro": "Pro",
  "subContent1": "Improve your drawing ability",
  "subContent2": "Unlock all Drawing templates collection",
  "subContent3": "Remove all ads",
  "subContent4": "Unlimited AR sketch",
  "lifeTime": "Lifetime",
  "yearly": "Yearly",
  "monthly": "Monthly",
  "weekly": "Weekly",
  "week": "Week",
  "only": "Only",
  "save": "Save",
  "share": "Share",
  "sketch": "Sketch",
  "trace": "Trace",
  "preview": "Preview",
  "txtContinue": "Continue",
  "connect": "Connect",
  "return": "Return",
  "print": "Print",
  "security": "Secured with Google Play. Cancel anytime",
  "bestSeller": "Best Seller",
  "lifeTimeContent": "Only one-time lifetime purchase",
  "album": "Album",
  "no_data": "No data",
  "deny_camera":
      "To start using the effect, please turn on\n access your camera",
  "open_settings": "Open settings",
  "please_wait": "Please wait",
  "video_not_support": "Video recording is not supported in this mode",
  "style": "Style",
  "stroke": "Stroke",
  "original": "Original",
  "opacity": "Opacity",
  "edge_level": "Edge level",
  "noise": "Noise",
  "tools": "Tools",
  "photo": "Photo",
  "record": "Record",
  "level": "Level",
  "beginner": "Beginner",
  "intermediate": "Intermediate",
  "advanced": "Advanced",
  "see_all": "See all",
  "sub_banner_1": "AR Draw sketch:\nEasily copy images\nto paper",
  "sub_banner_2": "Use Phone Camera\nto Draw",
  "sub_banner_3": "Preset Template\nto trace any photo",
  "sub_banner_4": "Improve\nyour drawing ability",
  "sub_banner_5": "Practice\nmake perfect",
  "upload_illus": "Upload your illustration",
  "my_album": "My album",
  "how_to_use": "How to use",
  "save_success": "Save success",
  "save_fail": "Save fail",
  "share_success": "Share success",
  "share_fail": "Share fail",
  "content_loading_ads": "Ads helps us maintain and develop\n free products",
  "camera": "Camera",
  "sub_rate_12": "Oh no! Please tell us what made you unsatisfied.",
  "sub_rate_3":
      "We're really sorry. We need your feedback to improve this app.",
  "sub_rate_4": "We love you too. Thanks for your feedback.",
  "sub_rate_5": "Wow, Awesome! Thank you so much.",
  "error": "Error",
  "check_internet_connection":
      "No Internet connection!\nPlease connect to the internet to continue using the app",
  "retry": "Retry",
  "choose_photo": "Choose photo",
  "choose_photo_warning": "Choose an image to start drawing now!!!",
  "exit_app": "Exit App?",
  "exit_app_content": "Do you want to exit the app?",
  "exit": "Exit",
  "print_content": "Turn the printer on and connect it",
  "deny_storage":
      "To start using this feature, please turn on\n access your storage",
  "permission": "Permission",
  "contentPermission": "This feature needs permission to work properly",
  "micro": "Microphone",
  "storage": "Storage",
};
