const frenchString = {
  "unknown_error": "Erreur inconnue",
  "no_internet": "Pas de connexion Internet",
  "not_available": "Indisponible",
  "can_not_connect_store": "Impossible de se connecter au magasin",
  "purchase_fail": "L'achat a échoué",
  "setting": "Réglages",
  "more": "Plus",
  "more_app": "Plus d'applications",
  "privacy_policy": "Politique de confidentialité",
  "term_of_condition": "Conditions d'utilisation",
  "term_of_service": "Conditions de service",
  "contact_us": "Contactez-nous",
  "restore": "Restaurer",
  "notice": "Remarque",
  "close": "Fermer",
  "continues": "Continuer",
  "errorLocation00":
      "Activez l'autorisation de localisation de l'appareil pour mettre à jour la température et les conditions météorologiques",
  "errorLocation01": "Veuillez activer les services de localisation",
  "errorLocation02":
      "Mettez à jour la température et les conditions météorologiques de votre emplacement en autorisant l'accès à votre emplacement précis",
  "errorLocation03":
      "Mettez à jour la température et les conditions météorologiques de votre emplacement en autorisant l'accès à votre emplacement précis",
  "intro1_1": "Apprenez à dessiner",
  "intro1_2": "",
  "intro1_3": "avec votre téléphone",
  "intro2_1": "Album de modèles",
  "intro2_2": "",
  "intro2_3": "pour dessiner tout",
  "intro3_1": "Copiez l'image sur le papier ",
  "intro3_2": "",
  "intro3_3": "avec l'esquisse AR",
  "intro4_1": "",
  "intro4_2": "Tracez avec",
  "intro4_3": " dessin incroyable",
  "str_remove_ads": "Trouver mon appareil",
  "remove_ads1": "Trouvez votre téléphone sans interruption",
  "remove_ads2": "Achat unique",
  "remove_ads3": "Accès à vie",
  "remove_ads4": "Supprimer les annonces pour toujours",
  "loading_ad": "Chargement des annonces...",
  "language": "Langue",
  "english": "Anglais",
  "next": "Suivant",
  "skip": "Passer",
  "request_per": "Demander la permission",
  "allow_per": "Autoriser la permission d'utiliser la fonction",
  "not_now": "Pas maintenant",
  "allow": "Autoriser",
  "record_permission": "Permission d'enregistrement",
  "cancel": "Annuler",
  "go_to_setting": "Aller aux paramètres",
  "OK": "OK",
  "no": "Non",
  "yes": "Oui",
  "close_app": "Fermer l'application",
  "want_exit": "Êtes-vous sûr de vouloir quitter?",
  "unlock_all": "Débloquer toutes les fonctionnalités",
  "ads_are_about": "Les annonces sont sur le point d'apparaître...",
  "loading": "Chargement...",
  "let_start": "Commencer",
  "notification": "Notification",
  "rate": "Évaluer",
  "draw": "Dessiner",
  "term": "Termes",
  "privacy": "Politique de confidentialité",
  "contact": "Contact",
  "goPremium": "Devenir Premium",
  "sub_rate":
      "Veuillez évaluer avec 5 étoiles pour nous motiver. Merci pour votre soutien!",
  "arDraw": "Dessin AR",
  "pro": "Pro",
  "subContent1": "Améliorez votre capacité de dessin",
  "subContent2": "Débloquez toute la collection de modèles de dessin",
  "subContent3": "Supprimez toutes les annonces",
  "subContent4": "Esquisse AR illimitée",
  "lifeTime": "Vie",
  "yearly": "Annuel",
  "monthly": "Mensuel",
  "weekly": "Hebdomadaire",
  "week": "Semaine",
  "only": "Seulement",
  "save": "Enregistrer",
  "share": "Partager",
  "sketch": "Esquisser",
  "trace": "Trace",
  "preview": "Aperçu",
  "txtContinue": "Continuer",
  "connect": "Connecter",
  "return": "Retourner",
  "print": "Imprimer",
  "security": "Sécurisé avec Google Play. Annulez à tout moment",
  "bestSeller": "Meilleures ventes",
  "lifeTimeContent": "Achat unique à vie",
  "album": "Album",
  "no_data": "Pas de données",
  "deny_camera":
      "Pour commencer à utiliser l'effet, veuillez activer l'accès à votre caméra",
  "open_settings": "Ouvrir les paramètres",
  "please_wait": "Veuillez patienter",
  "video_not_support":
      "L'enregistrement vidéo n'est pas pris en charge dans ce mode",
  "style": "Style",
  "stroke": "Coup de pinceau",
  "original": "Original",
  "opacity": "Opacité",
  "edge_level": "Niveau de bord",
  "noise": "Bruit",
  "tools": "Outils",
  "photo": "Photo",
  "record": "Enregistrement",
  "level": "Niveau",
  "beginner": "Débutant",
  "intermediate": "Intermédiaire",
  "advanced": "Avancé",
  "see_all": "Voir tout",
  "sub_banner_1": "Esquisse AR:\nCopiez facilement\ndes images\nsur du papier",
  "sub_banner_2": "Utilisez l'appareil\nphoto du\ntéléphone pour \ndessiner",
  "sub_banner_3": "Modèle prédéfini\npour tracer\nn'importe quelle\nphoto",
  "sub_banner_4": "Améliorez\nvotre capacité de\ndessin",
  "sub_banner_5": "La pratique\nfait la perfection",
  "upload_illus": "Téléchargez votre illustration",
  "my_album": "Mon album",
  "how_to_use": "Comment utiliser",
  "save_success": "Sauvegardé avec succès",
  "save_fail": "Échec de la sauvegarde",
  "share_success": "Partage réussi",
  "share_fail": "Échec du partage",
  "content_loading_ads":
      "Les annonces nous aident à maintenir et à développer\ndes produits gratuits",
  "camera": "Appareil photo",
  "sub_rate_12": "Oh non! S'il vous plaît, dites-nous ce qui vous a déçu.",
  "sub_rate_3":
      "Nous sommes vraiment désolés. Nous avons besoin de vos commentaires pour améliorer cette application.",
  "sub_rate_4": "Nous vous aimons aussi. Merci pour vos commentaires.",
  "sub_rate_5": "Wow, Génial! Merci beaucoup.",
  "error": "Erreur",
  "check_internet_connection":
      "Pas de connexion Internet !\nVeuillez vous connecter à Internet pour continuer à utiliser l'application",
  "retry": "Réessayer",
  "choose_photo": "Choisir une photo",
  "choose_photo_warning":
      "Choisissez une image pour commencer à dessiner maintenant !!!",
  "exit_app": "Quitter l'application ?",
  "exit_app_content": "Voulez-vous quitter l'application ?",
  "exit": "Quitter",
  "print_content": "Allumez l'imprimante et connectez-vous",
  "deny_storage":
      "Pour commencer à utiliser cette fonctionnalité, veuillez activer\n l'accès à votre stockage",
  "permission": "Autorisation",
  "contentPermission":
      "Cette fonctionnalité nécessite une autorisation pour fonctionner correctement",
  "micro": "Microphone",
  "storage": "Stockage",
};
