const germanyString = {
  "unknown_error": "Unbekannter Fehler",
  "no_internet": "Keine Internetverbindung",
  "not_available": "Nicht verfügbar",
  "can_not_connect_store": "Keine Verbindung zum Shop möglich",
  "purchase_fail": "Kauf fehlgeschlagen",
  "setting": "Einstellungen",
  "more": "Mehr",
  "more_app": "Mehr Apps",
  "privacy_policy": "Datenschutz-Bestimmungen",
  "term_of_condition": "Nutzungsbedingungen",
  "term_of_service": "Servicebedingungen",
  "contact_us": "Kontaktiere uns",
  "restore": "Wiederherstellen",
  "notice": "Hinweis",
  "close": "Schließen",
  "continues": "Fortfahren",
  "errorLocation00":
      "Aktivieren Sie die Geräteortungsberechtigung, um die Temperatur und die Wetterbedingungen zu aktualisieren",
  "errorLocation01": "Bitte aktivieren Sie die Standortdienste",
  "errorLocation02":
      "Aktualisieren Sie die Temperatur und die Wetterbedingungen Ihres Standorts, indem Sie den Zugriff auf Ihren genauen Standort zulassen",
  "errorLocation03":
      "Aktualisieren Sie die Temperatur und die Wetterbedingungen Ihres Standorts, indem Sie den Zugriff auf Ihren genauen Standort zulassen",
  "intro1_1": "Lernen Sie zu zeichnen",
  "intro1_2": "",
  "intro1_3": "mit Ihrem Telefon",
  "intro2_1": "Vorlagenalbum",
  "intro2_2": "",
  "intro2_3": "um alles zu zeichnen",
  "intro3_1": "Kopieren Sie das Bild auf Papier ",
  "intro3_2": "",
  "intro3_3": "mit AR-Skizze",
  "intro4_2": "Zeichnen Sie mit",
  "intro4_3": " erstaunlicher Zeichnung",
  "str_remove_ads": "Finde mein Gerät",
  "remove_ads1": "Finden Sie Ihr Telefon ohne Unterbrechung",
  "remove_ads2": "Einmaliger Kauf",
  "remove_ads3": "Lebenslanger Zugang",
  "remove_ads4": "Entfernen Sie Anzeigen für immer",
  "loading_ad": "Anzeigen werden geladen...",
  "language": "Sprache",
  "english": "Englisch",
  "next": "Nächster",
  "skip": "Überspringen",
  "request_per": "Berechtigung anfordern",
  "allow_per": "Berechtigung zum Verwenden der Funktion zulassen",
  "not_now": "Nicht jetzt",
  "allow": "Erlauben",
  "record_permission": "Aufnahmeberechtigung",
  "cancel": "Abbrechen",
  "go_to_setting": "Zu den Einstellungen gehen",
  "OK": "OK",
  "no": "Nein",
  "yes": "Ja",
  "close_app": "App schließen",
  "want_exit": "Möchten Sie wirklich beenden?",
  "unlock_all": "Alle Funktionen freischalten",
  "ads_are_about": "Anzeigen werden bald angezeigt...",
  "loading": "Laden...",
  "let_start": "Lass uns anfangen",
  "notification": "Benachrichtigung",
  "rate": "Bewerten",
  "draw": "Zeichnen",
  "term": "Bedingung",
  "privacy": "Datenschutzbestimmungen",
  "contact": "Kontakt",
  "goPremium": "Premium kaufen",
  "sub_rate":
      "Bitte bewerten Sie mit 5 Sternen, um uns zu motivieren. Danke für Ihre Unterstützung!",
  "arDraw": "AR zeichnen",
  "pro": "Profi",
  "subContent1": "Verbessern Sie Ihre Zeichenfähigkeiten",
  "subContent2": "Entsperren Sie alle Zeichnungsvorlagen",
  "subContent3": "Entfernen Sie alle Anzeigen",
  "subContent4": "Unbegrenzte AR-Skizze",
  "lifeTime": "Lebenslang",
  "yearly": "Jährlich",
  "monthly": "Monatlich",
  "weekly": "Wöchentlich",
  "week": "Woche",
  "only": "Nur",
  "save": "Speichern",
  "share": "Teilen",
  "sketch": "Skizze",
  "trace": "Spur",
  "preview": "Vorschau",
  "txtContinue": "Fortfahren",
  "connect": "Verbinden",
  "return": "Zurück",
  "print": "Drucken",
  "security": "Sicher mit Google Play. Jederzeit kündbar",
  "bestSeller": "Bestseller",
  "lifeTimeContent": "Nur einmaliger lebenslanger Kauf",
  "album": "Album",
  "no_data": "Keine Daten",
  "deny_camera":
      "Um mit dem Effekt zu beginnen, aktivieren Sie bitte den Zugriff auf Ihre Kamera",
  "open_settings": "Einstellungen öffnen",
  "please_wait": "Bitte warten",
  "video_not_support":
      "Die Videorekorderfunktion wird in diesem Modus nicht unterstützt",
  "style": "Stil",
  "stroke": "Strich",
  "original": "Original",
  "opacity": "Deckkraft",
  "edge_level": "Kantenstufe",
  "noise": "Rauschen",
  "tools": "Werkzeuge",
  "photo": "Foto",
  "record": "Aufzeichnung",
  "level": "Stufe",
  "beginner": "Anfänger",
  "intermediate": "Fortgeschritten",
  "advanced": "Experte",
  "see_all": "Alles anzeigen",
  "sub_banner_1": "AR-Skizze:\nKopieren Sie Bilder\neinfach auf Papier",
  "sub_banner_2": "Verwenden Sie die\nTelefonkamera\nzum Zeichnen",
  "sub_banner_3": "Vordefiniertes\nModell zum\nNachverfolgen\njedes Fotos",
  "sub_banner_4": "Verbessern\nSie Ihre\nZeichenfähigkeit",
  "sub_banner_5": "Übung\nmacht den Meister",
  "upload_illus": "Laden Sie Ihre Illustration hoch",
  "my_album": "Mein Album",
  "how_to_use": "Wie benutze ich",
  "save_success": "Erfolgreich gespeichert",
  "save_fail": "Speichern fehlgeschlagen",
  "share_success": "Erfolgreich geteilt",
  "share_fail": "Teilen fehlgeschlagen",
  "content_loading_ads":
      "Anzeigen helfen uns, kostenlose Produkte zu entwickeln und zu erhalten",
  "camera": "Kamera",
  "sub_rate_12":
      "Oh nein! Bitte sagen Sie uns, was Sie unzufrieden gemacht hat.",
  "sub_rate_3":
      "Es tut uns wirklich leid. Wir brauchen Ihr Feedback, um diese App zu verbessern.",
  "sub_rate_4": "Wir lieben dich auch. Danke für Ihr Feedback.",
  "sub_rate_5": "Wow, Super! Vielen Dank.",
  "error": "Fehler",
  "check_internet_connection":
      "Keine Internetverbindung!\nBitte verbinden Sie sich mit dem Internet, um die App weiter zu nutzen",
  "retry": "Erneut versuchen",
  "choose_photo": "Foto auswählen",
  "choose_photo_warning":
      "Wählen Sie ein Bild, um sofort mit dem Zeichnen zu beginnen!!!",
  "exit_app": "App verlassen?",
  "exit_app_content": "Möchten Sie die App verlassen?",
  "exit": "Verlassen",
  "print_content": "Schalten Sie den Drucker ein und verbinden Sie ihn",
  "deny_storage":
      "Um diese Funktion zu verwenden, aktivieren Sie bitte den Zugriff\n auf Ihren Speicher",
  "intro4_1": "",
  "permission": "Berechtigung",
  "contentPermission": "Diese Funktion benötigt eine Berechtigung, um ordnungsgemäß zu funktionieren",
  "micro": "Mikrofon",
  "storage": "Speicher",
};
