const indonesiaString = {
  "unknown_error": "Kesalahan tidak diketahui",
  "no_internet": "Tidak ada koneksi internet",
  "not_available": "Tidak tersedia",
  "can_not_connect_store": "Tidak dapat terhubung ke toko",
  "purchase_fail": "Pembelian gagal",
  "setting": "Pengaturan",
  "more": "Lebih banyak",
  "more_app": "Lebih banyak aplikasi",
  "privacy_policy": "Kebijakan Privasi",
  "term_of_condition": "Syarat dan Ketentuan",
  "term_of_service": "Syarat Layanan",
  "contact_us": "Hubungi kami",
  "restore": "Pulihkan",
  "notice": "Pemberitahuan",
  "close": "Tutup",
  "continues": "Lanjutkan",
  "errorLocation00":
      "Aktifkan izin lokasi perangkat untuk memperbarui suhu dan kondisi cuaca",
  "errorLocation01": "Silakan aktifkan layanan lokasi",
  "errorLocation02":
      "Perbarui suhu dan kondisi cuaca lokasi Anda dengan mengizinkan akses ke lokasi tepat Anda",
  "errorLocation03":
      "Perbarui suhu dan kondisi cuaca lokasi Anda dengan mengizinkan akses ke lokasi tepat Anda",
  "intro1_1": "Belajar menggambar",
  "intro1_2": "",
  "intro1_3": "dengan ponsel Anda",
  "intro2_1": "Album template",
  "intro2_2": "",
  "intro2_3": "untuk menggambar segala sesuatu",
  "intro3_1": "Salin gambar ke kertas ",
  "intro3_2": "",
  "intro3_3": "dengan sketsa AR",
  "intro4_1": "",
  "intro4_2": "Telusuri dengan",
  "intro4_3": "gambar mengagumkan",
  "str_remove_ads": "Cari Perangkat Saya",
  "remove_ads1": "Temukan telepon Anda tanpa terganggu",
  "remove_ads2": "Pembelian satu kali saja",
  "remove_ads3": "Akses seumur hidup",
  "remove_ads4": "Hapus iklan selamanya",
  "loading_ad": "Memuat iklan...",
  "language": "Bahasa",
  "english": "Inggris",
  "next": "Berikutnya",
  "skip": "Lewati",
  "request_per": "Minta izin",
  "allow_per": "Izinkan izin untuk menggunakan fungsi",
  "not_now": "Tidak sekarang",
  "allow": "Izinkan",
  "record_permission": "Izin rekaman",
  "cancel": "Batal",
  "go_to_setting": "Buka pengaturan",
  "OK": "OK",
  "no": "Tidak",
  "yes": "Ya",
  "close_app": "Tutup aplikasi",
  "want_exit": "Apakah Anda yakin ingin keluar?",
  "unlock_all": "Buka semua fitur",
  "ads_are_about": "Iklan akan ditampilkan segera...",
  "loading": "Memuat...",
  "let_start": "Ayo mulai",
  "notification": "Notifikasi",
  "rate": "Beri peringkat",
  "draw": "Gambar",
  "term": "Syarat",
  "privacy": "Kebijakan Privasi",
  "contact": "Kontak",
  "goPremium": "Upgrade ke Premium",
  "sub_rate":
      "Harap beri peringkat 5 bintang untuk memotivasi kami. Terima kasih atas dukungan Anda!",
  "arDraw": "Gambar AR",
  "pro": "Pro",
  "subContent1": "Tingkatkan kemampuan menggambar Anda",
  "subContent2": "Buka semua koleksi template menggambar",
  "subContent3": "Hapus semua iklan",
  "subContent4": "Sketsa AR tanpa batas",
  "lifeTime": "Seumur hidup",
  "yearly": "Tahunan",
  "monthly": "Bulanan",
  "weekly": "Mingguan",
  "week": "Minggu",
  "only": "Hanya",
  "save": "Simpan",
  "share": "Bagikan",
  "sketch": "Sketsa",
  "trace": "Jejak",
  "preview": "Pratinjau",
  "txtContinue": "Lanjutkan",
  "connect": "Hubungkan",
  "return": "Kembali",
  "print": "Cetak",
  "security": "Aman dengan Google Play. Bisa dibatalkan kapan saja",
  "bestSeller": "Penjual Terbaik",
  "lifeTimeContent": "Hanya satu kali pembelian seumur hidup",
  "album": "Album",
  "no_data": "Tidak ada data",
  "deny_camera":
      "Untuk memulai menggunakan efek, harap aktifkan akses kamera Anda",
  "open_settings": "Buka pengaturan",
  "please_wait": "Tunggu sebentar",
  "video_not_support": "Perekaman video tidak didukung dalam mode ini",
  "style": "Gaya",
  "stroke": "Goresan",
  "original": "Asli",
  "opacity": "Opasitas",
  "edge_level": "Tingkat tepi",
  "noise": "Kebisingan",
  "tools": "Alat",
  "photo": "Foto",
  "record": "Rekaman",
  "level": "Tingkat",
  "beginner": "Pemula",
  "intermediate": "Menengah",
  "advanced": "Mahir",
  "see_all": "Lihat semua",
  "sub_banner_1": "Sketsa AR:\nSalin gambar\ndengan mudah\nke kertas",
  "sub_banner_2": "Gunakan kamera\nponsel untuk\nmenggambar",
  "sub_banner_3": "Model Pra-set\nuntuk melacak \nsetiap foto",
  "sub_banner_4": "Tingkatkan\nkemampuan \nmenggambar Anda",
  "sub_banner_5": "Latihan\nmembuat sempurna",
  "upload_illus": "Unggah ilustrasi Anda",
  "my_album": "Album saya",
  "how_to_use": "Bagaimana cara menggunakan",
  "save_success": "Berhasil disimpan",
  "save_fail": "Gagal menyimpan",
  "share_success": "Berhasil dibagikan",
  "share_fail": "Gagal dibagikan",
  "content_loading_ads":
      "Iklan membantu kami mempertahankan dan mengembangkan\n produk gratis",
  "camera": "Kamera",
  "sub_rate_12":
      "Oh tidak! Tolong beritahu kami apa yang membuat Anda tidak puas.",
  "sub_rate_3":
      "Kami sangat menyesal. Kami membutuhkan umpan balik Anda untuk meningkatkan aplikasi ini.",
  "sub_rate_4": "Kami juga mencintai Anda. Terima kasih atas umpan balik Anda.",
  "sub_rate_5": "Wow, Luar Biasa! Terima kasih banyak.",
  "error": "Kesalahan",
  "check_internet_connection":
      "Tidak ada koneksi Internet!\nSilakan hubungkan ke internet untuk melanjutkan menggunakan aplikasi",
  "retry": "Coba lagi",
  "choose_photo": "Pilih foto",
  "choose_photo_warning": "Pilih gambar untuk mulai menggambar sekarang!!!",
  "exit_app": "Keluar dari aplikasi?",
  "exit_app_content": "Apakah Anda ingin keluar dari aplikasi?",
  "exit": "Keluar",
  "print_content": "Nyalakan printer dan hubungkan",
  "deny_storage":
      "Untuk mulai menggunakan fitur ini, harap aktifkan\n akses penyimpanan Anda",
  "permission": "Izin",
  "contentPermission": "Fitur ini memerlukan izin untuk bekerja dengan baik",
  "micro": "Mikrofon",
  "storage": "Penyimpanan",
};
