const portugueseString = {
  "unknown_error": "Erro desconhecido",
  "no_internet": "Sem conexão com a internet",
  "not_available": "Não disponível",
  "can_not_connect_store": "Não é possível conectar à loja",
  "purchase_fail": "A compra falhou",
  "setting": "Configurações",
  "more": "Mais",
  "more_app": "Mais aplicativos",
  "privacy_policy": "Política de Privacidade",
  "term_of_condition": "Termos de Condição",
  "term_of_service": "Termos de Serviço",
  "contact_us": "Contate-nos",
  "restore": "Restaurar",
  "notice": "Aviso",
  "close": "Fechar",
  "continues": "Continuar",
  "errorLocation00":
      "Ative a permissão de localização do dispositivo para atualizar a temperatura e as condições climáticas",
  "errorLocation01": "Por favor, habilite os serviços de localização",
  "errorLocation02":
      "Atualize a temperatura e as condições climáticas de sua localização permitindo o acesso à sua localização precisa",
  "errorLocation03":
      "Atualize a temperatura e as condições climáticas de sua localização permitindo o acesso à sua localização precisa",
  "intro1_1": "Aprenda a desenhar",
  "intro1_2": "",
  "intro1_3": "com seu telefone",
  "intro2_1": "Álbum de modelos",
  "intro2_2": "",
  "intro2_3": "para desenhar tudo",
  "intro3_1": "Copie a imagem para o papel ",
  "intro3_2": "",
  "intro3_3": "com o esboço de AR",
  "intro4_2": "Trace com",
  "intro4_3": " desenho incrível",
  "str_remove_ads": "Encontrar Meu Dispositivo",
  "remove_ads1": "Encontre seu telefone sem interrupções",
  "remove_ads2": "Compra única",
  "remove_ads3": "Acesso vitalício",
  "remove_ads4": "Remova os anúncios para sempre",
  "loading_ad": "Carregando anúncios...",
  "language": "Idioma",
  "english": "Inglês",
  "next": "Próximo",
  "skip": "Pular",
  "request_per": "Solicitar permissão",
  "allow_per": "Permitir permissão para usar a função",
  "not_now": "Agora não",
  "allow": "Permitir",
  "record_permission": "Permissão de Gravação",
  "cancel": "Cancelar",
  "go_to_setting": "Ir para Configurações",
  "OK": "OK",
  "no": "Não",
  "yes": "Sim",
  "close_app": "Fechar aplicativo",
  "want_exit": "Tem certeza de que deseja sair?",
  "unlock_all": "Desbloquear todos os recursos",
  "ads_are_about": "Os anúncios estão prestes a aparecer...",
  "loading": "Carregando...",
  "let_start": "Vamos começar",
  "notification": "Notificação",
  "rate": "Avaliar",
  "draw": "Desenhar",
  "term": "Termo",
  "privacy": "Política de privacidade",
  "contact": "Contato",
  "goPremium": "Obter Premium",
  "sub_rate":
      "Por favor, avalie com 5 estrelas para nos motivar. Obrigado pelo seu apoio!",
  "arDraw": "Desenho de AR",
  "pro": "Pro",
  "subContent1": "Melhore sua habilidade de desenho",
  "subContent2": "Desbloqueie toda a coleção de modelos de desenho",
  "subContent3": "Remova todos os anúncios",
  "subContent4": "Esboço de AR ilimitado",
  "lifeTime": "Vitalício",
  "yearly": "Anual",
  "monthly": "Mensal",
  "weekly": "Semanal",
  "week": "Semana",
  "only": "Apenas",
  "save": "Salvar",
  "share": "Compartilhar",
  "sketch": "Esboço",
  "trace": "Traçar",
  "preview": "Visualização",
  "txtContinue": "Continuar",
  "connect": "Conectar",
  "return": "Retornar",
  "print": "Imprimir",
  "security": "Seguro com o Google Play. Cancele a qualquer momento",
  "bestSeller": "Mais vendidos",
  "lifeTimeContent": "Compra única para a vida toda",
  "album": "Álbum",
  "no_data": "Sem dados",
  "deny_camera":
      "Para começar a usar o efeito, por favor, ative o acesso à sua câmera",
  "open_settings": "Abrir configurações",
  "please_wait": "Por favor, espere",
  "video_not_support": "A gravação de vídeo não é suportada neste modo",
  "style": "Estilo",
  "stroke": "Traço",
  "original": "Original",
  "opacity": "Opacidade",
  "edge_level": "Nível de borda",
  "noise": "Ruído",
  "tools": "Ferramentas",
  "photo": "Foto",
  "record": "Gravação",
  "level": "Nível",
  "beginner": "Iniciante",
  "intermediate": "Intermediário",
  "advanced": "Avançado",
  "see_all": "Ver tudo",
  "sub_banner_1": "Esboço de AR:\nCopie facilmente\nimagens para o\npapel",
  "sub_banner_2": "Use a câmera do\ntelefone para\ndesenhar",
  "sub_banner_3": "Modelo pré-definido\npara traçar\nqualquer foto",
  "sub_banner_4": "Melhore sua\nhabilidade de\ndesenho",
  "sub_banner_5": "Prática\nfaz a perfeição",
  "upload_illus": "Carregar sua ilustração",
  "my_album": "Meu álbum",
  "how_to_use": "Como usar",
  "save_success": "Salvo com sucesso",
  "save_fail": "Falha ao salvar",
  "share_success": "Compartilhado com sucesso",
  "share_fail": "Falha ao compartilhar",
  "content_loading_ads":
      "Os anúncios nos ajudam a manter e desenvolver\nprodutos gratuitos",
  "camera": "Câmera",
  "sub_rate_12": "Ah não! Por favor, nos diga o que te deixou insatisfeito.",
  "sub_rate_3":
      "Sentimos muito. Precisamos do seu feedback para melhorar este aplicativo.",
  "sub_rate_4": "Também te amamos. Obrigado pelo seu feedback.",
  "sub_rate_5": "Uau, impressionante! Muito obrigado.",
  "error": "Erro",
  "check_internet_connection":
      "Sem conexão com a internet!\nPor favor, conecte-se à internet para continuar usando o aplicativo",
  "retry": "Tentar novamente",
  "choose_photo": "Escolher foto",
  "choose_photo_warning": "Escolha uma imagem para começar a desenhar agora!!!",
  "exit_app": "Sair do aplicativo?",
  "exit_app_content": "Você deseja sair do aplicativo?",
  "exit": "Sair",
  "print_content": "Ligue a impressora e conecte-a",
  "deny_storage": "Para começar a usar esse recurso, por favor, ative\n o acesso ao seu armazenamento",
  "intro4_1": "",
  "permission": "Permissão",
  "contentPermission": "Esta funcionalidade precisa de permissão para funcionar corretamente",
  "micro": "Microfone",
  "storage": "Armazenamento",
};
