const spanishString = {
  "unknown_error": "Error desconocido",
  "no_internet": "No hay conexión a Internet",
  "not_available": "No disponible",
  "can_not_connect_store": "No se puede conectar a la tienda",
  "purchase_fail": "La compra ha fallado",
  "setting": "Configuración",
  "more": "Más",
  "more_app": "Más aplicaciones",
  "privacy_policy": "Política de privacidad",
  "term_of_condition": "Términos y condiciones",
  "term_of_service": "Términos del servicio",
  "contact_us": "Contáctenos",
  "restore": "Restaurar",
  "notice": "Aviso",
  "close": "Cerrar",
  "continues": "Continuar",
  "errorLocation00":
      "Habilitar permiso de ubicación del dispositivo para actualizar la temperatura y las condiciones climáticas",
  "errorLocation01": "Por favor, habilite los servicios de ubicación",
  "errorLocation02":
      "Actualice la temperatura y las condiciones climáticas de su ubicación permitiendo el acceso a su ubicación precisa",
  "errorLocation03":
      "Actualice la temperatura y las condiciones climáticas de su ubicación permitiendo el acceso a su ubicación precisa",
  "intro1_1": "Aprende a dibujar",
  "intro1_2": "",
  "intro1_3": "con tu teléfono",
  "intro2_1": "Álbum de plantillas",
  "intro2_2": "",
  "intro2_3": "para dibujar todo",
  "intro3_1": "Copia la imagen al papel ",
  "intro3_2": "",
  "intro3_3": "con el boceto de AR",
  "intro4_2": "Rastro con",
  "intro4_3": " increíble dibujo",
  "str_remove_ads": "Encontrar mi dispositivo",
  "remove_ads1": "Encuentra tu teléfono sin interrupciones",
  "remove_ads2": "Compra única",
  "remove_ads3": "Acceso de por vida",
  "remove_ads4": "Eliminar anuncios para siempre",
  "loading_ad": "Cargando anuncios...",
  "language": "Idioma",
  "english": "Inglés",
  "next": "Siguiente",
  "skip": "Omitir",
  "request_per": "Solicitar permiso",
  "allow_per": "Permitir permiso para usar la función",
  "not_now": "Ahora no",
  "allow": "Permitir",
  "record_permission": "Permiso de grabación",
  "cancel": "Cancelar",
  "go_to_setting": "Ir a ajustes",
  "OK": "Aceptar",
  "no": "No",
  "yes": "Sí",
  "close_app": "Cerrar aplicación",
  "want_exit": "¿Está seguro de que desea salir?",
  "unlock_all": "Desbloquear todas las funciones",
  "ads_are_about": "Los anuncios están a punto de aparecer...",
  "loading": "Cargando...",
  "let_start": "Comencemos",
  "notification": "Notificación",
  "rate": "Calificar",
  "draw": "Dibujar",
  "term": "Término",
  "privacy": "Política de privacidad",
  "contact": "Contacto",
  "goPremium": "Obtener Premium",
  "sub_rate":
      "Por favor califique con 5 estrellas para motivarnos. ¡Gracias por tu apoyo!",
  "arDraw": "Dibujo de RA",
  "pro": "Pro",
  "subContent1": "Mejora tu habilidad para dibujar",
  "subContent2": "Desbloquea toda la colección de plantillas de dibujo",
  "subContent3": "Elimina todos los anuncios",
  "subContent4": "Boceto de AR ilimitado",
  "lifeTime": "Vida",
  "yearly": "Anual",
  "monthly": "Mensual",
  "weekly": "Semanal",
  "week": "Semana",
  "only": "Solo",
  "save": "Guardar",
  "share": "Compartir",
  "sketch": "Boceto",
  "trace": "Rastro",
  "preview": "Vista previa",
  "txtContinue": "Continuar",
  "connect": "Conectar",
  "return": "Volver",
  "print": "Imprimir",
  "security": "Seguro con Google Play. Cancelar en cualquier momento",
  "bestSeller": "Más vendidos",
  "lifeTimeContent": "Compra única de por vida",
  "album": "Álbum",
  "no_data": "Sin datos",
  "deny_camera":
      "Para comenzar a usar el efecto, por favor active el acceso a su cámara",
  "open_settings": "Abrir ajustes",
  "please_wait": "Por favor espere",
  "video_not_support": "La grabación de video no es compatible en este modo",
  "style": "Estilo",
  "stroke": "Trazo",
  "original": "Original",
  "opacity": "Opacidad",
  "edge_level": "Nivel de borde",
  "noise": "Ruido",
  "tools": "Herramientas",
  "photo": "Foto",
  "record": "Grabar",
  "level": "Nivel",
  "beginner": "Principiante",
  "intermediate": "Intermedio",
  "advanced": "Avanzado",
  "see_all": "Ver todo",
  "sub_banner_1": "Boceto de AR:\nCopia fácilmente\nimágenes al papel",
  "sub_banner_2": "Usa la cámara del\nteléfono para\ndibujar",
  "sub_banner_3": "Plantilla\npreestablecida para\nrastrear cualquier\nfoto",
  "sub_banner_4": "Mejora tu\nhabilidad para\ndibujar",
  "sub_banner_5": "La práctica\nhace al maestro",
  "upload_illus": "Sube tu ilustración",
  "my_album": "Mi álbum",
  "how_to_use": "Cómo usar",
  "save_success": "Guardado exitosamente",
  "save_fail": "Error al guardar",
  "share_success": "Compartido exitosamente",
  "share_fail": "Error al compartir",
  "content_loading_ads":
      "Los anuncios nos ayudan a mantener y desarrollar\nproductos gratuitos",
  "camera": "Cámara",
  "sub_rate_12":
      "¡Oh no! Por favor, cuéntanos qué te hizo sentir insatisfecho.",
  "sub_rate_3":
      "Lo sentimos mucho. Necesitamos tu opinión para mejorar esta aplicación.",
  "sub_rate_4": "También te queremos. Gracias por tu opinión.",
  "sub_rate_5": "¡Guau, impresionante! Muchas gracias.",
  "error": "Error",
  "check_internet_connection":
      "¡Sin conexión a Internet!\nPor favor, conecte a Internet para continuar usando la aplicación",
  "retry": "Reintentar",
  "choose_photo": "Elegir foto",
  "choose_photo_warning":
      "¡Elige una imagen para empezar a dibujar ahora mismo!!!",
  "exit_app": "¿Salir de la aplicación?",
  "exit_app_content": "¿Desea salir de la aplicación?",
  "exit": "Salir",
  "print_content": "Encienda la impresora y conéctela",
  "deny_storage":
      "Para empezar a usar esta función, por favor, active\n el acceso a su almacenamiento",
  "intro4_1": "",
  "permission": "Permiso",
  "contentPermission":
      "Esta función necesita permiso para funcionar correctamente",
  "micro": "Micrófono",
  "storage": "Almacenamiento",
};
